<!DOCTYPE html>
<html>
<head>
 
    <meta charset='utf-8'>
    <meta content='IE=edge,chrome=1' http-equiv='X-UA-Compatible'>
    <title>磊山保經</title>
    <meta content="" name="keywords" >
    <meta content='' name='description'>
    <meta content='' name='author'>
    <meta content='width=device-width, initial-scale=1.0' name='viewport'>
    <link href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link href='stylesheets/style.css' rel='stylesheet'>

    <link href='stylesheets/ekko-lightbox.min.css' rel='stylesheet'>
    
    <!-- <script src='javascripts/modernizr-2.0.6.min.js'></script>  -->

    <!-- 引用jquery  -->
    <script type="text/javascript" src="//code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src='javascripts/jquery-ui-1.9.2.custom.min.js'></script>
    <script src='javascripts/jquery.transit.min.js'></script>
    <script src="javascripts/smooth-scroll.min.js"></script>
    
    <!-- 引用 bootstrap js -->
    <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <!-- 引用respond js -->
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
    
    <script src="//maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
    <script src='javascripts/ekko-lightbox.min.js'></script>
    <script src='javascripts/jquery.stellar.min.js'></script>
    
     <!-- Fav and touch icons -->
    <link rel="icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="img/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="img/favicon.png">


    <!--[if lt IE 8]>
    
    <![endif]-->
    <!--[if lt IE 9]>
    
    <![endif]-->
    <!--[if lt IE 10]>
    
    <![endif]-->
    

</head>
<body>

  <!-- slideshow -->
  <div class="bs-example" data-example-id="simple-carousel"> 
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel"> 
  <ol class="carousel-indicators" style="display: none;"> 
  <li data-target="#carousel-example-generic" data-slide-to="0" class=""></li> 
  <li data-target="#carousel-example-generic" data-slide-to="1" class="active"></li> 
  <li data-target="#carousel-example-generic" data-slide-to="2" class=""></li> 
  </ol> 
  <div class="carousel-inner" role="listbox"> 
  <div class="item active  slideshow">

  <img class="slideimg" alt="" src="image/slogan5.png" data-holder-rendered="true"> 
  
  </div> 
  <div class="item  slideshow"> 
  <div><h1>您好 歡迎來到磊山保經</h1></div>
  <img class="slideimg" alt="" src="image/ss1.png" data-holder-rendered="true"> 
  </div> 
  <div class="item slideshow"> 
  <div><h1>您好 歡迎來到磊山保經</h1></div>
  <img class="slideimg" alt="" src="image/ss2.png" data-holder-rendered="true"> 
  </div> 
   </div> 
   <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev"> 
    <div class="half-circle-left">
      <i class="fa fa-angle-left fa-3x"></i> 
      </div>
    </a> 
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next"> 
    <div class="half-circle-right">
      <i class="fa fa-angle-right fa-3x"></i> 
      </div>
    </a> 
   </div> 

    </div>


<!-- embed youtube -->

  <div class="embed-responsive embed-responsive-16by9"> 
    <iframe class="embed-responsive-item" src="//www.youtube.com/embed/V7ocZpIuAUY?rel=0" allowfullscreen=""></iframe> 
  </div>

<!-- menu -->

<div>
  <div class="menu-item">
    <a  href="customer">
      <h2 style="color: white;" class="menu-title">磊山客戶</h2>
      <img class="mask" src="image/mask.png">
      <img class="img-responsive" src="image/menu1.jpg"  alt="">
    </a>
    </div>
  <div class="menu-item">
    <a  href="intro">
      <h2 style="color: white;" class="menu-title">了解磊山</h2>
      <img class="mask" src="image/mask.png">
      <img class="img-responsive" src="image/menu2.jpg" alt="">
    </a>
    </div>
  <div class="menu-item">
    <a  href="join">
      <h2 style="color: white;" class="menu-title">加入磊山</h2>
      <img class="mask" src="image/mask.png">
      <img class="img-responsive" src="image/menu3.jpg" alt="">
    </a>
    </div>
</div>
<script src="javascripts/jquery.lazyload.min.js" type="text/javascript"></script>
<script src='javascripts/script.js'></script> 
  <script src='javascripts/intro.js'></script>
  <!-- <script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>
 -->
</body>
</html>